// <auto-generated />
using System;
using MealPlanOrganizer.Functions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealPlanOrganizer_Functions.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealPlanOrganizer.Functions.Data.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3f9a1b6-7c1b-4b33-b17b-0d2f9b2a5e01"),
                            CreatedUtc = new DateTime(2026, 1, 28, 13, 32, 37, 650, DateTimeKind.Utc).AddTicks(8329),
                            Description = "Classic lasagna with noodles and sauce",
                            Title = "Sample Lasagna"
                        });
                });

            modelBuilder.Entity("MealPlanOrganizer.Functions.Data.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Quantity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d3d5d7f-9a0c-4b3e-9f5a-2a9f7b6c1a11"),
                            Name = "noodles",
                            Quantity = "12 pieces",
                            RecipeId = new Guid("b3f9a1b6-7c1b-4b33-b17b-0d2f9b2a5e01")
                        },
                        new
                        {
                            Id = new Guid("7a2b6e9d-1c4f-4b82-8b8a-9b3c7a1d2f22"),
                            Name = "sauce",
                            Quantity = "2 cups",
                            RecipeId = new Guid("b3f9a1b6-7c1b-4b33-b17b-0d2f9b2a5e01")
                        });
                });

            modelBuilder.Entity("MealPlanOrganizer.Functions.Data.Entities.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9a1d2e3-4f5b-6c7d-8e9f-0a1b2c3d4e55"),
                            Instruction = "Boil noodles",
                            RecipeId = new Guid("b3f9a1b6-7c1b-4b33-b17b-0d2f9b2a5e01"),
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("f1e2d3c4-b5a6-7890-1a2b-3c4d5e6f7a88"),
                            Instruction = "Bake with sauce",
                            RecipeId = new Guid("b3f9a1b6-7c1b-4b33-b17b-0d2f9b2a5e01"),
                            StepNumber = 2
                        });
                });

            modelBuilder.Entity("MealPlanOrganizer.Functions.Data.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("MealPlanOrganizer.Functions.Data.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlanOrganizer.Functions.Data.Entities.RecipeStep", b =>
                {
                    b.HasOne("MealPlanOrganizer.Functions.Data.Entities.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlanOrganizer.Functions.Data.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
